# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 551)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(19, 29, 481, 501))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "border-radius: 30px;\n"
                                    "border-width: 5px 5px 5px 5px;\n"
                                    "border-style: solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(180, 410, 111, 41))
        self.pushButton.setStyleSheet("border-image: url(C:/Users/paulj/OneDrive/Desktop/GUIimages/loginbutton.png);")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(90, 120, 301, 61))
        self.email.setStyleSheet("font: 700 16pt \"Tahoma\";")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(90, 230, 301, 61))
        self.password.setStyleSheet("font: 700 16pt \"Tahoma\";")
        self.password.setObjectName("password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.email.setPlaceholderText(_translate("Form", "   Email"))
        self.password.setPlaceholderText(_translate("Form", "   Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
