# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUI(object):
    def setupUi(self, mainGUI):
        mainGUI.setObjectName("mainGUI")
        mainGUI.resize(473, 527)
        mainGUI.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(mainGUI)
        self.label.setGeometry(QtCore.QRect(-10, -10, 481, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\paulj\\OneDrive\\Desktop\\GUIimages\\ai.gif"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(mainGUI)
        self.pushButton.setGeometry(QtCore.QRect(40, 460, 121, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(C:/Users/paulj/OneDrive/Desktop/GUIimages/loginbutton.png);\n"
                                      "background-color: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainGUI)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 460, 121, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(C:/Users/paulj/OneDrive/Desktop/GUIimages/Regesterbutton.png);\n"
                                      "background-color: transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(mainGUI)
        QtCore.QMetaObject.connectSlotsByName(mainGUI)

    def retranslateUi(self, mainGUI):
        _translate = QtCore.QCoreApplication.translate
        mainGUI.setWindowTitle(_translate("mainGUI", "mainGUI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUI = QtWidgets.QWidget()
    ui = Ui_mainGUI()
    ui.setupUi(mainGUI)
    mainGUI.show()
    sys.exit(app.exec_())
